#!/usr/bin/env python3
"""Build configs/chapters.json identity metadata from learning_paths + runtime fields.

Runtime fields (chapter/algorithm/dataset/backend) are preserved from the existing
registry. Reading identity (id/family/title/tutorial/...) is merged from this
module's AUTHORITATIVE_ORDER. Display numbers are derived from learning_paths.book.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# id -> runtime chapter path + identity (family, title, reading_kind, ...)
AUTHORITATIVE_ORDER = [
    {
        "id": "loss-basics",
        "chapter": "preliminary",
        "algorithm": "loss-functions",
        "dataset": "fixtures",
        "backend": "native",
        "title": "损失函数与策略梯度基础",
        "family": "foundations",
        "reading_kind": "foundations",
        "tutorial": "preliminary/TUTORIAL.md",
        "prerequisites": [],
        "recommended_prerequisites": [],
        "concept_prerequisites": [],
        "entry": {"type": "python", "path": "examples/math/loss_walkthrough.py"},
        "runnable": True,
        "intended_level": "L0",
        "verified_level": "L0",
        "verified_note": "examples/math/reference/numerical_checks.json",
    },
    {
        "id": "ppo",
        "chapter": "001-ppo",
        "algorithm": "ppo",
        "dataset": "gsm8k",
        "backend": "trl",
        "title": "PPO：actor-critic、GAE 与裁剪更新",
        "family": "policy-preference",
        "reading_kind": "algorithm",
        "tutorial": "001-ppo/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["value-and-advantage", "ppo-clipping"],
        "entry": {"type": "yaml", "path": "001-ppo/config.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "CPU smoke via TRL; not paper reproduction",
    },
    {
        "id": "grpo",
        "chapter": "01-grpo",
        "algorithm": "grpo",
        "dataset": "gsm8k",
        "backend": "trl",
        "title": "GRPO：同题采样与组内优势",
        "family": "policy-preference",
        "reading_kind": "algorithm",
        "tutorial": "01-grpo/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": ["ppo"],
        "concept_prerequisites": ["behavior-ratio", "ppo-clipping"],
        "entry": {"type": "yaml", "path": "01-grpo/config.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "TRL default; verl GPU check exists separately",
    },
    {
        "id": "dapo",
        "chapter": "06-dapo",
        "algorithm": "dapo",
        "dataset": "dapo",
        "backend": "verl",
        "title": "DAPO：动态采样、裁剪与长度处理",
        "family": "policy-preference",
        "reading_kind": "algorithm",
        "tutorial": "06-dapo/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["mask-and-reduction"],
        "entry": {"type": "yaml", "path": "06-dapo/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Local recipe; not full paper pipeline",
    },
    {
        "id": "gspo",
        "chapter": "07-gspo",
        "algorithm": "gspo",
        "dataset": "dapo",
        "backend": "trl",
        "title": "GSPO：序列级比率与裁剪",
        "family": "policy-preference",
        "reading_kind": "algorithm",
        "tutorial": "07-gspo/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["behavior-ratio"],
        "entry": {"type": "yaml", "path": "07-gspo/config.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Teaching implementation",
    },
    {
        "id": "dpo",
        "chapter": "002-dpo",
        "algorithm": "dpo",
        "dataset": "dpo",
        "backend": "trl",
        "title": "DPO：从偏好对直接优化策略",
        "family": "policy-preference",
        "reading_kind": "algorithm",
        "tutorial": "002-dpo/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["preference-loss"],
        "entry": {"type": "yaml", "path": "002-dpo/config.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Synthetic GSM8K-derived pairs; not human preference study",
    },
    {
        "id": "search-r1",
        "chapter": "03-search-r1",
        "algorithm": "search-r1",
        "dataset": "hotpot",
        "backend": "verl",
        "title": "Search-R1：学习检索与观察 mask",
        "family": "tools-multimodal",
        "reading_kind": "system",
        "tutorial": "03-search-r1/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["mask-and-reduction"],
        "entry": {"type": "yaml", "path": "03-search-r1/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Local BM25 corpus, not live web search",
    },
    {
        "id": "retool",
        "chapter": "05-retool",
        "algorithm": "retool",
        "dataset": "dapo",
        "backend": "verl",
        "title": "ReTool：真实执行与工具决策",
        "family": "tools-multimodal",
        "reading_kind": "system",
        "tutorial": "05-retool/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": ["search-r1"],
        "concept_prerequisites": ["mask-and-reduction"],
        "entry": {"type": "yaml", "path": "05-retool/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Restricted numeric Python tool",
    },
    {
        "id": "alfworld",
        "chapter": "08-alfworld",
        "algorithm": "alfworld",
        "dataset": "alfworld-manifests",
        "backend": "verl",
        "title": "ALFWorld：有状态环境中的策略学习",
        "family": "tools-multimodal",
        "reading_kind": "environment",
        "tutorial": "08-alfworld/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": ["retool"],
        "concept_prerequisites": ["mdp-and-observation", "terminal-and-truncation"],
        "entry": {"type": "yaml", "path": "08-alfworld/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "TextWorld interface; not robot success rate",
    },
    {
        "id": "vision-grpo",
        "chapter": "09-vision-grpo",
        "algorithm": "vision-grpo",
        "dataset": "geoqa",
        "backend": "verl",
        "title": "Vision-GRPO：图像条件下的策略学习",
        "family": "tools-multimodal",
        "reading_kind": "application",
        "tutorial": "09-vision-grpo/TUTORIAL.md",
        "prerequisites": ["grpo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": [],
        "entry": {"type": "yaml", "path": "09-vision-grpo/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Input plumbing vs capability must stay separate",
    },
    {
        "id": "general-opd",
        "chapter": "02-opd/general-opd",
        "algorithm": "opd",
        "dataset": "deepmath",
        "backend": "verl",
        "title": "General OPD：学生采样与教师反馈",
        "family": "distillation",
        "reading_kind": "algorithm",
        "tutorial": "02-opd/general-opd/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": ["grpo"],
        "concept_prerequisites": ["kl-and-entropy", "behavior-ratio"],
        "entry": {"type": "yaml", "path": "02-opd/general-opd/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Sampled reverse-KL surrogate, not all OPD definitions",
    },
    {
        "id": "opsd",
        "chapter": "04-opsd",
        "algorithm": "opsd",
        "dataset": "opsd",
        "backend": "verl",
        "title": "OPSD：特权信息与自教师",
        "family": "distillation",
        "reading_kind": "algorithm",
        "tutorial": "04-opsd/TUTORIAL.md",
        "prerequisites": ["general-opd"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["kl-and-entropy"],
        "entry": {"type": "yaml", "path": "04-opsd/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Fixed step-0 teacher is local setting",
    },
    {
        "id": "medical-sar-idt",
        "chapter": "02-opd",
        "algorithm": "sar-opd",
        "dataset": "medical",
        "backend": "verl",
        "title": "Medical OPD / SAR / IDT：领域调度案例",
        "family": "distillation",
        "reading_kind": "case-study",
        "tutorial": "02-opd/TUTORIAL.md",
        "prerequisites": ["general-opd"],
        "recommended_prerequisites": ["opsd"],
        "concept_prerequisites": [],
        "entry": {"type": "yaml", "path": "02-opd/config.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Domain schedule labels; not clinical capability",
    },
    {
        "id": "agentopsd",
        "chapter": "09-AgentOPSD",
        "algorithm": "agentopsd",
        "dataset": "alfworld-manifests",
        "backend": "verl",
        "title": "AgentOPSD：自教师辅助的轮次信用",
        "family": "distillation",
        "reading_kind": "algorithm",
        "tutorial": "09-AgentOPSD/TUTORIAL.md",
        "prerequisites": ["alfworld", "opsd", "grpo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": [],
        "entry": {"type": "yaml", "path": "09-AgentOPSD/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Cross-listed under tools/long-horizon in family pages",
    },
    {
        "id": "tempo",
        "chapter": "09-tempo",
        "algorithm": "tempo",
        "dataset": "alfworld-manifests",
        "backend": "verl",
        "title": "TEMPO：短分支、估值与状态恢复",
        "family": "long-horizon",
        "reading_kind": "advanced-implementation",
        "tutorial": "09-tempo/TUTORIAL.md",
        "prerequisites": ["alfworld", "ppo"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["value-and-advantage", "terminal-and-truncation"],
        "entry": {"type": "yaml", "path": "09-tempo/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "Local implementation study; official page incomplete at review",
    },
    {
        "id": "harness-rl",
        "chapter": "12-harness-rl",
        "algorithm": "harness-rl",
        "dataset": "hotpot",
        "backend": "verl",
        "title": "Harness-RL：调用记录与参数分区",
        "family": "long-horizon",
        "reading_kind": "system",
        "tutorial": "12-harness-rl/TUTORIAL.md",
        "prerequisites": ["retool"],
        "recommended_prerequisites": ["alfworld"],
        "concept_prerequisites": ["mask-and-reduction"],
        "entry": {"type": "yaml", "path": "12-harness-rl/verl.yaml"},
        "runnable": True,
        "intended_level": "L1",
        "verified_level": "L1",
        "verified_note": "central-only MLP partition",
    },
    {
        "id": "td3",
        "chapter": "14-td3",
        "algorithm": "td3",
        "dataset": "embodied/fetch-reach",
        "backend": "embodied",
        "title": "TD3：确定性策略与双 Q 稳定化",
        "family": "control-offline",
        "reading_kind": "algorithm",
        "tutorial": "14-td3/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["value-and-advantage", "replay-and-offline", "continuous-density"],
        "entry": {"type": "python", "path": "14-td3/train.py"},
        "runnable": True,
        "intended_level": "L2",
        "verified_level": "L1",
        "verified_note": "CPU smoke + FetchReach physics; stable gain not published here",
    },
    {
        "id": "sac",
        "chapter": "13-sac",
        "algorithm": "sac",
        "dataset": "embodied/fetch-reach",
        "backend": "embodied",
        "title": "SAC：随机策略与最大熵目标",
        "family": "control-offline",
        "reading_kind": "algorithm",
        "tutorial": "13-sac/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": ["td3"],
        "concept_prerequisites": ["continuous-density", "replay-and-offline"],
        "entry": {"type": "python", "path": "13-sac/train.py"},
        "runnable": True,
        "intended_level": "L2",
        "verified_level": "L1",
        "verified_note": "Target actions from current actor in local SAC path",
    },
    {
        "id": "her",
        "chapter": "15-her",
        "algorithm": "her",
        "dataset": "embodied/fetch-reach",
        "backend": "embodied",
        "title": "HER：目标条件经验重标记",
        "family": "control-offline",
        "reading_kind": "data-relabel",
        "tutorial": "15-her/TUTORIAL.md",
        "prerequisites": ["td3"],
        "recommended_prerequisites": [],
        "concept_prerequisites": ["replay-and-offline"],
        "entry": {"type": "python", "path": "15-her/train.py"},
        "runnable": True,
        "intended_level": "L2",
        "verified_level": "L1",
        "verified_note": "Local TD3+HER; not a separate her_loss",
    },
    {
        "id": "iql",
        "chapter": "16-iql",
        "algorithm": "iql",
        "dataset": "embodied/fetch-reach",
        "backend": "embodied",
        "title": "IQL：固定数据、expectile 与加权模仿",
        "family": "control-offline",
        "reading_kind": "algorithm",
        "tutorial": "16-iql/TUTORIAL.md",
        "prerequisites": ["loss-basics"],
        "recommended_prerequisites": ["td3"],
        "concept_prerequisites": ["replay-and-offline", "expectile"],
        "entry": {"type": "python", "path": "16-iql/train.py"},
        "runnable": True,
        "intended_level": "L2",
        "verified_level": "L1",
        "verified_note": "Offline training steps are not environment interaction steps",
    },
]


def main() -> None:
    chapters_path = ROOT / "configs/chapters.json"
    paths = json.loads((ROOT / "configs/learning_paths.json").read_text(encoding="utf-8"))
    book = paths["book"]
    by_id = {row["id"]: row for row in AUTHORITATIVE_ORDER}
    if book != [row["id"] for row in AUTHORITATIVE_ORDER]:
        raise SystemExit("learning_paths.book must match AUTHORITATIVE_ORDER ids")
    registry = []
    for display_no, chapter_id in enumerate(book, start=1):
        row = dict(by_id[chapter_id])
        row["display_number"] = display_no
        registry.append(row)
    chapters_path.write_text(
        json.dumps(registry, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {chapters_path} ({len(registry)} chapters)")


if __name__ == "__main__":
    main()
